[project]
name = "group4-all-in-one-healthcare"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "pyside6>=6.9.0",
    "simplematch>=1.4",
    "tzlocal>=5.3.1",
]
